inputScreen:
  title: "&3宝可梦商店"
  text: "&r输入你想要购买的宝可梦名字"
gui:
  title: "&7购买{pokemon}"
  pokeInfo:
    name: "&3{pokemon}"
    lore:
      - "&7支付类型: &a{paytype}"
      - "&7价格: {value}"
  confirm:
    name: "&a确认"
    lore:
      - "&a确认购买,精灵将会添加到你背包或者PC"
      - "&c如果没有设置价格,点击后会申请价格"
payTypeFormat:
  none: "&6未设置"
  points: "&3点券"
  vault: "&6金币"
Msg:
  help:
    - 'help'
    - 'reload'
    - 'open'
    - 'applylist'
  reload: '&a配置已经重载!'
  incorrectName: '&c错误名字!'
  purchaseSuccessful: '&a购买成功!'
  notEnoughMoney: "&c您没有足够的货币!"
  currencyNotExist: "&c货币类型不存在!"
  noPriceSet: "&c付款类型和付款费用未设置！§7(申请已添加!)"
  enterNonNumber: "&c输入的不是数字!"
  editedSuccessfully: "&a编辑成功!"